// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrjcrlxoqcahujimtnez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyamNybHhvcWNhaHVqaW10bmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTc5NDgsImV4cCI6MjA2NjE5Mzk0OH0.VdRvlOPta4qkBz5aTvpDTZWVH0EIlbBVitZhZMfNaCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);